### ISSUE TITLE
No statistics change in 'Verification in progress' window

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#104] opened 2022-04-13 09:04 UTC
**Describe the bug**
When you start a verification, a 'Verification in progress' pop-up window is opened. This window provide statistics on CPU time and memory usage. Yet, when I run queries, non of these values seem to change. For example, CPU time used remains having the values `0s / 0s / 0s`. 

**To Reproduce**
1. Open any model.
2. Go to Verifier tab
3. Run a query (ideally one that take some time, so you can actually see the pop-up window)
4. See that nothing changes.

**Expected behavior**
The values change according to what currently is being used by the engine.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 9.

**Screenshots**
![Screenshot 2022-04-13 at 11 03 54](https://user-images.githubusercontent.com/36483423/163141081-95afcfc2-851c-4542-acfc-e5db094d65e3.png)

**Desktop (please complete the following information):**
- Version: UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
- OS: Ubuntu 20.04.3 LTS, running as a virtual machine with VirtualBox 6.1.32 on MacOS 12.2.1
- Java version: openjdk version "11.0.13" 2021-10-19, OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04), OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing).

**Comment by RasmusRendal** [comment] 2022-05-16 11:38
I could not reproduce it in stratego 9, using the `train-gate.xml` example with `N = 60;` and the query `A[] forall (i : id_t) forall (j : id_t) Train(i).Cross && Train(j).Cross imply i == j`. Do you have an example of a model that exhibits this behaviour?

**Comment by magoorden** [comment] 2022-05-18 13:14
> I could not reproduce it in stratego 9, using the `train-gate.xml` example with `N = 60;` and the query `A[] forall (i : id_t) forall (j : id_t) Train(i).Cross && Train(j).Cross imply i == j`. Do you have an example of a model that exhibits this behaviour?

I see that for this one the window indeed updates. For a query where it does not upgrade is in the `stratego/cruise.xml` model using query `strategy safe = control: A[] distance > 5`. Below I screen captured what I experienced (10x speed).

https://user-images.githubusercontent.com/36483423/169047131-b5fb5b9a-2daa-4063-93e0-9e2ce11c1ece.mp4

**Comment by RasmusRendal** [comment] 2022-05-18 13:19
Alright, I could reproduce the issue in stratego 9, but it seems to have been fixed on the development branch. Thank you for the update

**Comment by mikucionisaau** [comment] 2022-10-06 07:29
Fix released with Stratego-10

**Closed as completed by mikucionisaau** 2022-10-06 07:29 UTC
Labels: waiting for release
