### ISSUE TITLE
Cannot generate diagnostic traces from the GUI with UPPAAL 4.1.20-stratego-9 under macOS

### ISSUE THREAD

**Issue by pacalet** [UPPAALModelChecker/UPPAAL-Meta#78] opened 2022-02-24 09:04 UTC
**Describe the bug**
With UPPAAL 4.1.20-stratego-9 the GUI normally opens a popup offering to store a counter-example trace in the simulator when a property fails in the Verifier tab. This does not happen under macOS 12.1 (Monterey).

**To Reproduce**
Open the UPPAAL 4.1.20-stratego-9 GUI under macOS  12.1 (Monterey). Load the [provided system model][1], check the _Some_ option of the _Engine Options / Diagnostic Trace_ menu, verify the property. It should fail but no popup appears. When doing exactly the same under, e.g., Debian 11.2 (Bullseye), the popup appears.

**Expected behavior**
A popup offering to store the trace in the simulator should showup.

**Version(s) of UPPAAL tested**
Does not work in UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022, macOS Monterey 12.1. Works in UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022, Debian 11.2 (Bullseye).

**Screenshots**
Expected popup:
![popup][2]

**Desktop (please complete the following information):**
 - UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
 - macOS Monterey 12.1

[1]: https://github.com/UPPAALModelChecker/UPPAAL-Meta/files/8131097/bug.txt
[2]: https://user-images.githubusercontent.com/45038397/155492867-9ae15796-b5c0-4676-8634-164fa8327774.png

**Comment by magoorden** [comment] 2022-03-03 15:56
Maybe I have something related. I'm running Stratego 9 in a virtual Ubuntu with MacOS 12.2.1 as a host. Sometimes the generation of a trace also fails, and it will generate a segmentation fault (`Server received SIGSEGV signal`). But rerunning the same query immediately again does result in the expected pop-up indicating whether we want to store the new trace in the simulator.
Unfortunately, I haven't found a way to consistently get this error.

**Comment by yrke** [comment] 2022-03-07 07:17
I can confirm the issue on MacOS version 11.6.4 using the app bundle

**Comment by mikucionisaau** [comment] 2022-08-02 08:49
Seems to be fixed in UPPAAL-4.1.20-stratego-10-beta6-app (or earlier), at least I could not reproduce the issue: it successfully generates a trace and loads it into Symbolic Simulator.
Tested on macOS 12.5 Monterey.

**Closed as completed** 2022-10-03 14:28 UTC
Labels: bug, stratego, confirmed, critical, MacOS
