### ISSUE TITLE
Linux: Internet connection is required for activation

### ISSUE THREAD

**Issue by yrke** [UPPAALModelChecker/UPPAAL-Meta#75] opened 2022-02-14 12:12 UTC
**Describe the bug**
When starting UPPAAL GUI on some linux distros you are met with an error and the following is printed to the terminal
```
Internet connection is required for activation.
Internet connection is required for activation.
Internet connection is required for activation.
Unknown protocol version: {"#error": "Server received SIGABRT signal"}
```

If running ./engine by hand gives a similar error. 

**To Reproduce**
1. Open UPPAAL GUI or run engine
2. Observe error

**Version(s) of UPPAAL tested**
We have received error report on this issue targeting, UPPAAL 4.1.26 and UPPAAL Stratego 4.1.2-stratego9.

**Desktop (please complete the following information):**
We have received report targeting the following platforms: 
  - Fedora
  - Xubuntu 21.10

**Additional context**
It seems the error is linked to the bundled libc version. Removing this solves the problem. 
Possible workaround: 

```
rm bin-Linux/{ld-linux.so,libc.so.6,libgcc_s.so.1,libpthread.so.0,libstdc++.so.6,libdl.so.2,libm.so.6,librt.so.1}
mv bin-Linux/{server.bin,server}
mv bin-Linux/{verifyta.bin,verifyta}
```

** Original Report **
This issue was originally reported by Jan Kofron and Peter Gjøl Jensen.

**Comment by mikucionisaau** [comment] 2022-02-14 14:38
If the workaround works, we need to know what library we are missing. Could you run `ldd bin-Linux/server.bin` on such a system?
Also, what is the kernel version?

**Comment by petergjoel** [comment] 2022-02-14 16:55
I experience this on Fedora with 5.15.18-200.fc35.x86_64. 

I get the following from ldd:
```
ldd bin/server.bin 
	linux-vdso.so.1 (0x00007fff7877f000)
	libdl.so.2 => /home/pgj/uppaal-4.1.20-stratego-9-linux64/bin/libdl.so.2 (0x00007ff94b68a000)
	libprlearn.so => /home/pgj/Devel/uppaal/server/build/linux64/lib/libprlearn.so (0x00007ff94b674000)
	libstrategy.so => /home/pgj/Devel/uppaal/server/build/linux64/lib/libstrategy.so (0x00007ff94b635000)
	libpthread.so.0 => /home/pgj/uppaal-4.1.20-stratego-9-linux64/bin/libpthread.so.0 (0x00007ff94b612000)
	libstdc++.so.6 => /home/pgj/uppaal-4.1.20-stratego-9-linux64/bin/libstdc++.so.6 (0x00007ff94b430000)
	libm.so.6 => /home/pgj/uppaal-4.1.20-stratego-9-linux64/bin/libm.so.6 (0x00007ff94b2df000)
	libgcc_s.so.1 => /home/pgj/uppaal-4.1.20-stratego-9-linux64/bin/libgcc_s.so.1 (0x00007ff94b2c4000)
	libc.so.6 => /home/pgj/uppaal-4.1.20-stratego-9-linux64/bin/libc.so.6 (0x00007ff94b0d2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff94bd84000)
```
It looks as if libprlearn and libstrategy are picked up from the wrong location.

**Comment by mikucionisaau** [comment] 2022-02-15 13:36
@petergjoel do you have something special in your environment? perhaps `LD_LIBRARY_PATH` or similar pointing to `/home/pgj/Devel/uppaal/server/build/linux64/lib/` ?

**Comment by davidlaewen** [comment] 2022-03-24 11:25
The same issue exists on Manjaro 5.15.25-1 with OpenJDK 11.0.15 and can be fixed with @yrke's workaround

**Comment by c-andy-candies** [comment] 2022-05-26 10:05
Same issue on Arch Linux.

Output of `ldd bin-Linux/server.bin`:
`
        linux-vdso.so.1 (0x00007ffc7b96b000)
        libpthread.so.0 => /home/andrea/Downloads/uppaal/uppaal64-4.1.26-1/bin-Linux/libpthread.so.0 (0x00007fd06158d000)
        libstdc++.so.6 => /home/andrea/Downloads/uppaal/uppaal64-4.1.26-1/bin-Linux/libstdc++.so.6 (0x00007fd061381000)
        libm.so.6 => /home/andrea/Downloads/uppaal/uppaal64-4.1.26-1/bin-Linux/libm.so.6 (0x00007fd06123e000)
        libgcc_s.so.1 => /home/andrea/Downloads/uppaal/uppaal64-4.1.26-1/bin-Linux/libgcc_s.so.1 (0x00007fd061224000)
        libc.so.6 => /home/andrea/Downloads/uppaal/uppaal64-4.1.26-1/bin-Linux/libc.so.6 (0x00007fd06105c000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fd061b06000)
`

I tried with both OpenJDK 18.0.1.1 and 11.0.15 and both had the same error. 

My env:
`
COLORFGBG=0;15
COLORTERM=truecolor
CUDA_PATH=/opt/cuda
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DEBUGINFOD_URLS=https://debuginfod.archlinux.org 
DISPLAY=:0
GDK_DPI_SCALE=1
GDK_SCALE=1
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/andrea/.gtkrc-2.0:/home/andrea/.config/gtkrc-2.0
GTK_RC_FILES=/etc/gtk/gtkrc:/home/andrea/.gtkrc:/home/andrea/.config/gtkrc
HOME=/home/andrea
INVOCATION_ID=9ecd4fb06f244b858785e9eab8ae59a1
KDE_APPLICATIONS_AS_SCOPE=1
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
KONSOLE_DBUS_SERVICE=:1.38
KONSOLE_DBUS_SESSION=/Sessions/1
KONSOLE_DBUS_WINDOW=/Windows/1
KONSOLE_VERSION=220401
LANG=en_US.UTF-8
LANGUAGE=en-US.UTF-8
LC_TIME=it_IT.UTF-8
LESS=-R
LOGNAME=andrea
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:
MAIL=/var/spool/mail/andrea
MKLROOT=/opt/intel/mkl
MOTD_SHOWN=pam
MOZ_ENABLE_WAYLAND=1
OLDPWD=/home/andrea
P9K_SSH=0
P9K_TTY=old
PAGER=less
PATH=/home/andrea/bin:/usr/local/bin:/home/andrea/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/andrea/.gem/ruby/3.0.0/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PLASMA_USE_QT_SCALING=1
PROFILEHOME=
PWD=/home/andrea
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_WAYLAND_FORCE_DPI=96
SESSION_MANAGER=local/archtop:@/tmp/.ICE-unix/3146,unix/archtop:/tmp/.ICE-unix/3146
SHELL=/bin/zsh
SHELL_SESSION_ID=409a003dd5f14bc3a2dc1911cdc016fc
SHLVL=2
SYSTEMD_EXEC_PID=2178
TERM=xterm-256color
TMOUT=300
USER=andrea
WAYLAND_DISPLAY=wayland-0
WINDOWID=1
XAUTHORITY=/run/user/1000/xauth
XCURSOR_SIZE=24
XCURSOR_THEME=breeze_cursors
XDG_ACTIVATION_TOKEN=kwin-6
XDG_CONFIG_DIRS=/home/andrea/.config/kdedefaults:/etc/xdg
XDG_CURRENT_DESKTOP=KDE
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_ID=1
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
XKB_DEFAULT_LAYOUT=it
XKB_DEFAULT_VARIANT=,qwerty
_=/usr/bin/env
_P9K_TTY=/dev/pts/0
LC_CTYPE=
`

@yrke's workaround fixed it but weird thing: after fixing it I retried unzipping the program again to see if I could reproduce it again  and now even the "non fixed one" doesn't give any error even though it still has the bundled libraries untouched. Perhaps it can see that my IP has already activated it or something?

**Comment by mikucionisaau** [comment] 2022-06-08 05:27
1) Java has nothing to do with it.
2) The issue is with `libc` version conflict. 

We ship our own `libc` library so that `server.bin`/`verifyta.bin` could be run on systems with older `libc` (especially cluster/grid computing facilities which tend to be very conservative).
Latest Fedora, Ubuntu, Arch Linux usually ship newer `libc` version.
My guess is that the internet ping triggers loading some network library from the host which is not included in Uppaal distribution which required the newer `libc` version from host, which leads to version conflict and failure. Such a library can be almost anything: from DNS lookup to firewall, thus difficult to predict what it may require.
If the `libc` is removed from Uppaal distribution and `server.bin`/`verifyta.bin` run directly (Kenneth's workaround), then the host's `libc` is used, which is newer and compatible with all the libraries (backward compatible with Uppaal and compatible with the rest of host libraries), and thus everything is fine.

**Comment by mikucionisaau** [comment] 2022-10-07 08:46
Stratego-10 has the following solution:
- GUI attempts to use the `bin/server`: the native binary using the host's `libc` etc., which is important with newer `libc` (network domain lookup, firewall, also dynamic library loading from within the model).
- If GUI fails to execute `bin/server` (e.g. host's `libc` is too old), it will fall back to `bin/server.sh` which is a wrapper script which loads the shipped `libc` and is important for older systems (e.g. grid/cluster computing).

Feel free to reopen if the problem persists.

**Closed as completed by mikucionisaau** 2022-10-07 08:46 UTC
Labels: bug
