### ISSUE TITLE
Invalid int initializer reported in `/system` instead of the correct position

### ISSUE THREAD

**Issue by magoorden** [UPPAALModelChecker/UPPAAL-Meta#87] opened 2022-03-14 10:52 UTC
**Describe the bug**
Consider having a model with a wrong int initializer, for example `int i = 0.2;`. When you check the model for syntax errors, this initialization error is reported as coming from `/system` instead of the correct position in the model.

**To Reproduce**
1. Open a new model.
2. Add `int i = 0.2;` to `Declarations`.
3. Check for syntax errors (`Tools` -> `Check Syntax` or F7).
4. Observe `Invalid initializer` error with position `/system`.
5. If you go to `System Declarations`, you will see a tiny red dot after `system Process;`.

**Expected behavior**
The position of the error should indicate the correct position in the model.

**Version(s) of UPPAAL tested**
UPPAAL Stratego 9.

**Desktop (please complete the following information):**
- Version: UPPAAL 4.1.20-stratego-9 (rev. 67D95DBCE6B8B4ED), January 2022
- OS: Ubuntu 20.04.3 LTS, running as a virtual machine with VirtualBox 6.1.32 on MacOS 12.2.1
- Java version: openjdk version "11.0.13" 2021-10-19, OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04), OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing).

**Comment by RasmusRendal** [comment] 2022-03-14 11:03
This seems to be a duplicate of https://github.com/UPPAALModelChecker/UPPAAL-Meta/issues/76. The issue is not present on the development branch.

**Closed as completed by RasmusRendal** 2022-03-14 11:03 UTC
